### ISSUE TITLE
Complete DB Seed files

### ISSUE THREAD

**Issue by jateeter** [GreenButtonAlliance/OpenESPI-Common-java#130]
It is now necessary to have all db rows completely loaded during the seed of the databases. This is especially needed for the dynamic registration issues in the DataCustodian and ThirdParty projects, but also needed in the SFTP and Bulk implementations.  Following completion, any residual NULL entries should have documentation as to why they are still NULL for clarity.

**Comment by jateeter** [comment]
The services.greenbuttondata.org seed files are not complete with respect to ApplicationInformation. So all that is left is to replicate the seeds used for the Testing configuration

**Comment by dfcoffin** [comment]
Closing as database Script files now exist to initialize database
